export const clubBadges: Record<string, string> = {
  "Arsenal": "/club-badges/Arsenal FC.png",
  "Chelsea": "/club-badges/Chelsea FC.png",
  "Liverpool": "/club-badges/Liverpool FC.png",
  "Man City": "/club-badges/Manchester City.png",
  "Manchester City": "/club-badges/Manchester City.png",
  "Man United": "/club-badges/Manchester United.png",
  "Manchester United": "/club-badges/Manchester United.png",
  "Tottenham": "/club-badges/Tottenham Hotspur.png",
  "Tottenham Hotspur": "/club-badges/Tottenham Hotspur.png",
  "Aston Villa": "/club-badges/Aston Villa.png",
  "Bournemouth": "/club-badges/Bournemouth.png",
  "Brentford": "/club-badges/Brentford.png",
  "Brighton": "/club-badges/Brighton.png",
  "Brighton & Hove Albion": "/club-badges/Brighton.png",
  "Burnley": "/club-badges/Burnley.png",
  "Crystal Palace": "/club-badges/Crystal Palace.png",
  "Everton": "/club-badges/Everton.png",
  "Fulham": "/club-badges/Fulham FC.png",
  "Ipswich": "/club-badges/Ipswich Town.png",
  "Ipswich Town": "/club-badges/Ipswich Town.png",
  "Leeds": "/club-badges/Leeds United.png",
  "Leeds United": "/club-badges/Leeds United.png",
  "Newcastle": "/club-badges/Newcastle United.png",
  "Newcastle United": "/club-badges/Newcastle United.png",
  "Nottingham Forest": "/club-badges/Nottm Forest.png",
  "Sunderland": "/club-badges/Sunderland.png",
  "West Ham": "/club-badges/West Ham United.png",
  "West Ham United": "/club-badges/West Ham United.png",
  "Wolves": "/club-badges/Wolverhampton Wanderers.png",
  "Wolverhampton": "/club-badges/Wolverhampton Wanderers.png",
  "Wolverhampton Wanderers": "/club-badges/Wolverhampton Wanderers.png",
  "Hull": "/club-badges/Hull City.png",
  "Hull City": "/club-badges/Hull City.png",
  "Nottm Forest": "/club-badges/Nottm Forest.png",
  "Birmingham": "/club-badges/birmingham city.png",
  "Birmingham City": "/club-badges/birmingham city.png",
  "Blackburn": "/club-badges/blackburn rovers.png",
  "Blackburn Rovers": "/club-badges/blackburn rovers.png",
  "Bolton": "/club-badges/bolton wanderers.png",
  "Bolton Wanderers": "/club-badges/bolton wanderers.png",
  "Bristol City": "/club-badges/Bristol City.png",
  "Cardiff": "/club-badges/Cardiff City.png",
  "Cardiff City": "/club-badges/Cardiff City.png",
  "Charlton": "/club-badges/Charlton Athletic.png",
  "Charlton Athletic": "/club-badges/Charlton Athletic.png",
  "Coventry": "/club-badges/Coventry City.png",
  "Coventry City": "/club-badges/Coventry City.png",
  "Derby": "/club-badges/Derby County.png",
  "Derby County": "/club-badges/Derby County.png",
  "Middlesbrough": "/club-badges/Middlesbrough.png",
  "Millwall": "/club-badges/Millwall.png",
  "Portsmouth": "/club-badges/Portsmouth.png",
  "Preston": "/club-badges/Preston.png",
  "Preston North End": "/club-badges/Preston.png",
  "QPR": "/club-badges/Queens Park Rangers.png",
  "Queens Park Rangers": "/club-badges/Queens Park Rangers.png",
  "Sheffield United": "/club-badges/Sheffield United.png",
  "Southampton": "/club-badges/Southampton.png",
  "Stoke": "/club-badges/Stoke City.png",
  "Stoke City": "/club-badges/Stoke City.png",
  "Swansea": "/club-badges/Swansea City.png",
  "Swansea City": "/club-badges/Swansea City.png",
  "Watford": "/club-badges/Watford.png",
  "West Brom": "/club-badges/West Bromwich Albion.png",
  "West Bromwich Albion": "/club-badges/West Bromwich Albion.png",
  "Wrexham": "/club-badges/Wrexham.png",
  "Sheffield Utd": "/club-badges/Sheffield United.png",
  "Sheffield Wednesday": "/club-badges/Sheffield Wednesday.png",
  "Sheff Wednesday": "/club-badges/Sheffield Wednesday.png",
  "Norwich": "/club-badges/Norwich City.png",
  "Norwich City": "/club-badges/Norwich City.png",
  "Accrington": "/club-badges/Accrington Stanley.png",
  "Accrington Stanley": "/club-badges/Accrington Stanley.png",
  "Barnet": "/club-badges/Barnet.png",
  "Barnsley": "/club-badges/Barnsley.png",
  "Blackpool": "/club-badges/Blackpool.png",
  "Bradford": "/club-badges/Bradford.png",
  "Bradford City": "/club-badges/Bradford.png",
  "Bristol Rovers": "/club-badges/Bristol Rovers.png",
  "Bromley": "/club-badges/Bromley.png",
  "Burton": "/club-badges/Burton.png",
  "Burton Albion": "/club-badges/Burton.png",
  "Cambridge": "/club-badges/Cambridge United.png",
  "Cambridge United": "/club-badges/Cambridge United.png",
  "Cheltenham": "/club-badges/Cheltenham.png",
  "Cheltenham Town": "/club-badges/Cheltenham.png",
  "Colchester": "/club-badges/Colchester United.png",
  "Colchester United": "/club-badges/Colchester United.png",
  "Crawley": "/club-badges/Crawley Town.png",
  "Crawley Town": "/club-badges/Crawley Town.png",
  "Crewe": "/club-badges/Crewe.png",
  "Crewe Alexandra": "/club-badges/Crewe.png",
  "Doncaster": "/club-badges/Doncaster Rovers.png",
  "Doncaster Rovers": "/club-badges/Doncaster Rovers.png",
  "Exeter": "/club-badges/Exeter City.png",
  "Exeter City": "/club-badges/Exeter City.png",
  "Fleetwood": "/club-badges/Fleetwood Town.png",
  "Fleetwood Town": "/club-badges/Fleetwood Town.png",
  "Gillingham": "/club-badges/Gillingham.png",
  "Grimsby": "/club-badges/Grimsby Town.png",
  "Grimsby Town": "/club-badges/Grimsby Town.png",
  "Huddersfield": "/club-badges/Huddersfield.png",
  "Huddersfield Town": "/club-badges/Huddersfield.png",
  "Leyton Orient": "/club-badges/Leyton Orient.png",
  "Lincoln": "/club-badges/Lincoln City.png",
  "Lincoln City": "/club-badges/Lincoln City.png",
  "Mansfield": "/club-badges/Mansfield.png",
  "Mansfield Town": "/club-badges/Mansfield.png",
  "MK Dons": "/club-badges/Mk dons.png",
  "Milton Keynes Dons": "/club-badges/Mk dons.png",
  "Newport": "/club-badges/Newport County.png",
  "Newport County": "/club-badges/Newport County.png",
  "Northampton": "/club-badges/Northampton Town.png",
  "Northampton Town": "/club-badges/Northampton Town.png",
  "Notts County": "/club-badges/Notts County.png",
  "Oldham": "/club-badges/Oldham Athletic.png",
  "Oldham Athletic": "/club-badges/Oldham Athletic.png",
  "Oxford": "/club-badges/Oxford United.png",
  "Oxford United": "/club-badges/Oxford United.png",
  "Peterborough": "/club-badges/Peterborough.png",
  "Peterborough United": "/club-badges/Peterborough.png",
  "Plymouth": "/club-badges/Plymouth Argyle.png",
  "Plymouth Argyle": "/club-badges/Plymouth Argyle.png",
  "Port Vale": "/club-badges/Port Vale.png",
  "Rochdale": "/club-badges/Rochdale.png",
  "Rotherham": "/club-badges/Rotherham United.png",
  "Rotherham United": "/club-badges/Rotherham United.png",
  "Salford": "/club-badges/Salford City.png",
  "Salford City": "/club-badges/Salford City.png",
  "Shrewsbury": "/club-badges/Shrewsbury Town.png",
  "Shrewsbury Town": "/club-badges/Shrewsbury Town.png",
  "Stevenage": "/club-badges/Stevenage.png",
  "Stockport": "/club-badges/Stockport County.png",
  "Stockport County": "/club-badges/Stockport County.png",
  "Swindon": "/club-badges/Swindon Town.png",
  "Swindon Town": "/club-badges/Swindon Town.png",
  "Tranmere": "/club-badges/Tranmere Rovers.png",
  "Tranmere Rovers": "/club-badges/Tranmere Rovers.png",
  "Walsall": "/club-badges/Walsall.png",
  "Wigan": "/club-badges/Wigan Athletic.png",
  "Wigan Athletic": "/club-badges/Wigan Athletic.png",
  "Wycombe": "/club-badges/Wycombe Wanderers.png",
  "Wycombe Wanderers": "/club-badges/Wycombe Wanderers.png",
  "York": "/club-badges/York City.png",
  "York City": "/club-badges/York City.png",
  "Leicester": "/club-badges/Leicester City.png",
  "Leicester City": "/club-badges/Leicester City.png",
  "Luton": "/club-badges/Luton.png",
  "Luton Town": "/club-badges/Luton.png",
  "Aberdeen": "/club-badges/Aberdeen.png",
  "Celtic": "/club-badges/Celtic FC.png",
  "Dundee": "/club-badges/Dundee FC.png",
  "Dundee FC": "/club-badges/Dundee FC.png",
  "Dundee United": "/club-badges/Dundee United.png",
  "Dundee Utd": "/club-badges/Dundee United.png",
  "Falkirk": "/club-badges/Falkirk FC.png",
  "Heart of Midlothian": "/club-badges/Heart of Midlothian FC.png",
  "Hearts": "/club-badges/Heart of Midlothian FC.png",
  "Hibernian": "/club-badges/Hibernian FC.png",
  "Hibs": "/club-badges/Hibernian FC.png",
  "Kilmarnock": "/club-badges/Kilmarnock FC.png",
  "Motherwell": "/club-badges/Motherwell FC.png",
  "Rangers": "/club-badges/Rangers FC.png",
  "St Mirren": "/club-badges/St. Mirren FC.png",
  "St. Mirren": "/club-badges/St. Mirren FC.png",
  "St Johnstone": "/club-badges/St. Johnstone FC.png",
  "St. Johnstone": "/club-badges/St. Johnstone FC.png",
  "Athletic Bilbao": "/club-badges/Athletic Bilbao.png",
  "Athletic Club": "/club-badges/Athletic Bilbao.png",
  "Barcelona": "/club-badges/FC Barcelona.png",
  "FC Barcelona": "/club-badges/FC Barcelona.png",
  "Osasuna": "/club-badges/CA Osasuna.png",
  "CA Osasuna": "/club-badges/CA Osasuna.png",
  "Celta Vigo": "/club-badges/Celta de Vigo.png",
  "Celta de Vigo": "/club-badges/Celta de Vigo.png",
  "Elche": "/club-badges/Elche CF.png",
  "Elche CF": "/club-badges/Elche CF.png",
  "Espanyol": "/club-badges/RCD Espanyol Barcelona.png",
  "RCD Espanyol": "/club-badges/RCD Espanyol Barcelona.png",
  "RCD Espanyol Barcelona": "/club-badges/RCD Espanyol Barcelona.png",
  "Getafe": "/club-badges/Getafe CF.png",
  "Getafe CF": "/club-badges/Getafe CF.png",
  "Levante": "/club-badges/Levante UD.png",
  "Levante UD": "/club-badges/Levante UD.png",
  "Rayo Vallecano": "/club-badges/Rayo Vallecano.png",
  "Real Betis": "/club-badges/Real Betis Balompié.png",
  "Real Betis Balompié": "/club-badges/Real Betis Balompié.png",
  "Real Madrid": "/club-badges/Real Madrid.png",
  "Real Sociedad": "/club-badges/Real Sociedad.png",
  "Sevilla": "/club-badges/Sevilla FC.png",
  "Sevilla FC": "/club-badges/Sevilla FC.png",
  "Valencia": "/club-badges/Valencia CF.png",
  "Valencia CF": "/club-badges/Valencia CF.png",
  "Villarreal": "/club-badges/Villarreal CF.png",
  "Villarreal CF": "/club-badges/Villarreal CF.png",
  "Alavés": "/club-badges/Deportivo Alavés.png",
  "Deportivo Alavés": "/club-badges/Deportivo Alavés.png",
  "Atletico Madrid": "/club-badges/Atlético de Madrid.png",
  "Atlético Madrid": "/club-badges/Atlético de Madrid.png",
  "Atlético de Madrid": "/club-badges/Atlético de Madrid.png",
  "Angers": "/club-badges/Angers SCO.png",
  "Angers SCO": "/club-badges/Angers SCO.png",
  "Auxerre": "/club-badges/AJ Auxerre.png",
  "AJ Auxerre": "/club-badges/AJ Auxerre.png",
  "Brest": "/club-badges/Stade Brestois 29.png",
  "Stade Brestois": "/club-badges/Stade Brestois 29.png",
  "Stade Brestois 29": "/club-badges/Stade Brestois 29.png",
  "Le Havre": "/club-badges/Le Havre AC.png",
  "Le Havre AC": "/club-badges/Le Havre AC.png",
  "Lens": "/club-badges/RC Lens.png",
  "RC Lens": "/club-badges/RC Lens.png",
  "Lille": "/club-badges/LOSC Lille.png",
  "LOSC Lille": "/club-badges/LOSC Lille.png",
  "Lorient": "/club-badges/Lorient FC.png",
  "FC Lorient": "/club-badges/Lorient FC.png",
  "Lyon": "/club-badges/Olympique Lyon.png",
  "Olympique Lyon": "/club-badges/Olympique Lyon.png",
  "Olympique Lyonnais": "/club-badges/Olympique Lyon.png",
  "Marseille": "/club-badges/Olympique Marseille.png",
  "Olympique Marseille": "/club-badges/Olympique Marseille.png",
  "Olympique de Marseille": "/club-badges/Olympique Marseille.png",
  "Monaco": "/club-badges/AS Monaco.png",
  "AS Monaco": "/club-badges/AS Monaco.png",
  "Nice": "/club-badges/OGC Nice.png",
  "OGC Nice": "/club-badges/OGC Nice.png",
  "Paris FC": "/club-badges/Paris FC.png",
  "Paris Saint-Germain": "/club-badges/Paris Saint-Germain.png",
  "Paris Saint Germain": "/club-badges/Paris Saint-Germain.png",
  "PSG": "/club-badges/Paris Saint-Germain.png",
  "Rennes": "/club-badges/Stade Rennais FC.png",
  "Stade Rennais": "/club-badges/Stade Rennais FC.png",
  "Stade Rennais FC": "/club-badges/Stade Rennais FC.png",
  "Strasbourg": "/club-badges/RC Strasbourg Alsace.png",
  "RC Strasbourg": "/club-badges/RC Strasbourg Alsace.png",
  "RC Strasbourg Alsace": "/club-badges/RC Strasbourg Alsace.png",
  "Toulouse": "/club-badges/FC Toulouse.png",
  "Toulouse FC": "/club-badges/FC Toulouse.png",
  "Troyes": "/club-badges/ESTAC Troyes.png",
  "ESTAC Troyes": "/club-badges/ESTAC Troyes.png",
  "Le Mans": "/club-badges/Le Mans FC.png",
  "Le Mans FC": "/club-badges/Le Mans FC.png",
  "Atalanta": "/club-badges/Atalanta BC.png",
  "Atalanta BC": "/club-badges/Atalanta BC.png",
  "Bologna": "/club-badges/Bologna FC 1909.png",
  "Bologna FC": "/club-badges/Bologna FC 1909.png",
  "Cagliari": "/club-badges/Cagliari Calcio.png",
  "Cagliari Calcio": "/club-badges/Cagliari Calcio.png",
  "Como": "/club-badges/Como 1907.png",
  "Como 1907": "/club-badges/Como 1907.png",
  "Fiorentina": "/club-badges/ACF Fiorentina.png",
  "ACF Fiorentina": "/club-badges/ACF Fiorentina.png",
  "Frosinone": "/club-badges/Frosinone Calcio.png",
  "Frosinone Calcio": "/club-badges/Frosinone Calcio.png",
  "Genoa": "/club-badges/Genoa CFC.png",
  "Genoa CFC": "/club-badges/Genoa CFC.png",
  "Inter": "/club-badges/Inter Milan.png",
  "Inter Milan": "/club-badges/Inter Milan.png",
  "Juventus": "/club-badges/Juventus FC.png",
  "Juventus FC": "/club-badges/Juventus FC.png",
  "Lazio": "/club-badges/SS Lazio.png",
  "SS Lazio": "/club-badges/SS Lazio.png",
  "Lecce": "/club-badges/US Lecce.png",
  "US Lecce": "/club-badges/US Lecce.png",
  "AC Milan": "/club-badges/AC Milan.png",
  "Milan": "/club-badges/AC Milan.png",
  "Monza": "/club-badges/AC Monza.png",
  "AC Monza": "/club-badges/AC Monza.png",
  "Napoli": "/club-badges/SSC Napoli.png",
  "SSC Napoli": "/club-badges/SSC Napoli.png",
  "Parma": "/club-badges/Parma Calcio 1913.png",
  "Parma Calcio": "/club-badges/Parma Calcio 1913.png",
  "Parma Calcio 1913": "/club-badges/Parma Calcio 1913.png",
  "Roma": "/club-badges/AS Roma.png",
  "AS Roma": "/club-badges/AS Roma.png",
  "Sassuolo": "/club-badges/US Sassuolo.png",
  "US Sassuolo": "/club-badges/US Sassuolo.png",
  "Torino": "/club-badges/Torino FC.png",
  "Torino FC": "/club-badges/Torino FC.png",
  "Udinese": "/club-badges/Udinese Calcio.png",
  "Udinese Calcio": "/club-badges/Udinese Calcio.png",
  "Venezia": "/club-badges/Venezia FC.png",
  "Venezia FC": "/club-badges/Venezia FC.png",
  "Augsburg": "/club-badges/FC Augsburg.png",
  "FC Augsburg": "/club-badges/FC Augsburg.png",
  "Bayern Munich": "/club-badges/Bayern Munich.png",
  "Bayern": "/club-badges/Bayern Munich.png",
  "Bayer Leverkusen": "/club-badges/Bayer 04 Leverkusen.png",
  "Bayer 04 Leverkusen": "/club-badges/Bayer 04 Leverkusen.png",
  "Borussia Dortmund": "/club-badges/Borussia Dortmund.png",
  "Dortmund": "/club-badges/Borussia Dortmund.png",
  "Borussia Mönchengladbach": "/club-badges/Borussia Mönchengladbach.png",
  "Borussia Monchengladbach": "/club-badges/Borussia Mönchengladbach.png",
  "Mönchengladbach": "/club-badges/Borussia Mönchengladbach.png",
  "Monchengladbach": "/club-badges/Borussia Mönchengladbach.png",
  "Eintracht Frankfurt": "/club-badges/Eintracht Frankfurt.png",
  "Frankfurt": "/club-badges/Eintracht Frankfurt.png",
  "Freiburg": "/club-badges/SC Freiburg.png",
  "SC Freiburg": "/club-badges/SC Freiburg.png",
  "Hamburg": "/club-badges/Hamburger SV.png",
  "Hamburger SV": "/club-badges/Hamburger SV.png",
  "Hoffenheim": "/club-badges/TSG 1899 Hoffenheim.png",
  "TSG Hoffenheim": "/club-badges/TSG 1899 Hoffenheim.png",
  "TSG 1899 Hoffenheim": "/club-badges/TSG 1899 Hoffenheim.png",
  "Köln": "/club-badges/1.FC Köln.png",
  "Koln": "/club-badges/1.FC Köln.png",
  "FC Köln": "/club-badges/1.FC Köln.png",
  "1. FC Köln": "/club-badges/1.FC Köln.png",
  "Mainz": "/club-badges/1.FSV Mainz 05.png",
  "Mainz 05": "/club-badges/1.FSV Mainz 05.png",
  "1. FSV Mainz 05": "/club-badges/1.FSV Mainz 05.png",
  "RB Leipzig": "/club-badges/RB Leipzig.png",
  "Leipzig": "/club-badges/RB Leipzig.png",
  "Union Berlin": "/club-badges/1.FC Union Berlin.png",
  "1. FC Union Berlin": "/club-badges/1.FC Union Berlin.png",
  "Werder Bremen": "/club-badges/SV Werder Bremen.png",
  "SV Werder Bremen": "/club-badges/SV Werder Bremen.png",
  "Stuttgart": "/club-badges/VfB Stuttgart.png",
  "VfB Stuttgart": "/club-badges/VfB Stuttgart.png",
  "Schalke": "/club-badges/FC Schalke 04.png",
  "Schalke 04": "/club-badges/FC Schalke 04.png",
  "FC Schalke 04": "/club-badges/FC Schalke 04.png",
  "Paderborn": "/club-badges/SC Paderborn 07.png",
  "SC Paderborn": "/club-badges/SC Paderborn 07.png",
  "Elversberg": "/club-badges/SV 07 Elversberg.png",
  "SV Elversberg": "/club-badges/SV 07 Elversberg.png",
};